"""One-line agent install (sprint v0.5.0-prod #8).

Usage from any Linux/macOS shell:

    curl https://mcp.xn----8sbwawqx4fza.xn--p1ai/onboard.sh | bash -s <agent-id> [project]

Result:
  - Agent registered via POST /agents/register
  - Personal api_key saved to ~/.cognitive-core/credentials (chmod 600)
  - Claude Desktop / Cursor JSON snippet printed for copy-paste
  - First heartbeat sent to confirm working

The script is self-contained — no Python dependency on the client side
(uses curl + small POSIX shell). Endpoint returns text/x-shellscript so
piping into bash is the canonical install path.
"""
from fastapi import APIRouter, Query
from fastapi.responses import PlainTextResponse

router = APIRouter(tags=["onboard"])


_SCRIPT = r"""#!/usr/bin/env bash
# Cognitive Core — agent onboarding
# Generated by https://mcp.xn----8sbwawqx4fza.xn--p1ai/onboard.sh

set -euo pipefail

AGENT_ID="${1:-${AGENT_ID:-}}"
PROJECT="${2:-${PROJECT:-default}}"
MACHINE="${MACHINE:-$(hostname)}"
API_BASE="${API_BASE:-https://mcp.xn----8sbwawqx4fza.xn--p1ai}"

if [ -z "$AGENT_ID" ]; then
    cat <<'USAGE' >&2
Usage:
  curl <onboard-url> | bash -s <agent-id> [project]
  AGENT_ID=my-agent PROJECT=foo curl <onboard-url> | bash

Examples:
  curl https://mcp.xn----8sbwawqx4fza.xn--p1ai/onboard.sh | bash -s claude-desktop-laptop
  curl https://mcp.xn----8sbwawqx4fza.xn--p1ai/onboard.sh | bash -s ai-crm-deploy ai-crm
USAGE
    exit 1
fi

# Validate agent_id format (matches server-side regex ^[a-zA-Z0-9_-]+$)
if ! echo "$AGENT_ID" | grep -qE '^[a-zA-Z0-9_-]+$'; then
    echo "ERROR: agent_id must match ^[a-zA-Z0-9_-]+$ (got: $AGENT_ID)" >&2
    exit 1
fi

echo "==> Registering agent '$AGENT_ID' for project '$PROJECT' on '$MACHINE'..."

RESPONSE=$(curl -sS --max-time 10 -X POST "$API_BASE/agents/register" \
    -H "Content-Type: application/json" \
    -d "{\"agent_id\":\"$AGENT_ID\",\"project\":\"$PROJECT\",\"machine\":\"$MACHINE\",\"description\":\"Onboarded via curl|bash\"}")

# Extract api_key — try jq first (clean), fallback to grep+sed
if command -v jq >/dev/null 2>&1; then
    API_KEY=$(echo "$RESPONSE" | jq -r .api_key)
else
    API_KEY=$(echo "$RESPONSE" | grep -oE '"api_key":"[^"]+"' | sed 's/"api_key":"//;s/"//')
fi

if [ -z "$API_KEY" ] || [ "$API_KEY" = "null" ]; then
    echo "ERROR: register failed. Response:" >&2
    echo "$RESPONSE" >&2
    exit 1
fi

# Save credentials locally (chmod 600)
CONFIG_DIR="$HOME/.cognitive-core"
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

cat > "$CONFIG_DIR/credentials" <<EOF
# Cognitive Core agent credentials — KEEP PRIVATE
# Generated by onboard.sh on $(date -Iseconds)
COGNITIVE_API_URL=$API_BASE
COGNITIVE_API_KEY=$API_KEY
COGNITIVE_AGENT_NAME=$AGENT_ID
COGNITIVE_PROJECT=$PROJECT
EOF
chmod 600 "$CONFIG_DIR/credentials"

# Confirm with first heartbeat
HEARTBEAT_RESP=$(curl -sS --max-time 5 -X POST "$API_BASE/agents/heartbeat" \
    -H "X-API-Key: $API_KEY" -H "Content-Type: application/json" \
    -d '{"current_task":"just onboarded"}')

if echo "$HEARTBEAT_RESP" | grep -q '"ok":true'; then
    echo "==> Heartbeat OK — agent registered and active"
else
    echo "WARNING: heartbeat failed. Response: $HEARTBEAT_RESP" >&2
fi

cat <<'BANNER'

╔════════════════════════════════════════════════════════════════════╗
║  ✅ Agent registered. Credentials in ~/.cognitive-core/credentials ║
╚════════════════════════════════════════════════════════════════════╝

Use it now:
BANNER

cat <<EOF
  # Quick check — see who's online:
  curl -H "X-API-Key: \$COGNITIVE_API_KEY" $API_BASE/agents/online | jq

  # Send DM to another agent:
  curl -X POST $API_BASE/agents/message \\
       -H "X-API-Key: \$COGNITIVE_API_KEY" -H "Content-Type: application/json" \\
       -d '{"to":"<other-agent-id>","text":"hello"}'

  # Read my inbox:
  curl -H "X-API-Key: \$COGNITIVE_API_KEY" "$API_BASE/agents/inbox?since_minutes=60" | jq

For Claude Desktop / Cursor MCP, add to claude_desktop_config.json:

{
  "mcpServers": {
    "cognitive-core": {
      "command": "npx",
      "args": ["-y", "mcp-remote@latest",
               "$API_BASE/mcp/sse",
               "--header", "X-API-Key:$API_KEY"]
    }
  }
}

Restart Claude Desktop. You'll get tools: cognitive_remember,
cognitive_recall, cognitive_send, cognitive_inbox, cognitive_online,
cognitive_heartbeat, and more.
EOF
"""


@router.get("/onboard.sh", response_class=PlainTextResponse)
async def onboard_script(_: str | None = Query(None)):
    """Return the onboarding bash script. Pipe into bash to register a new agent."""
    return PlainTextResponse(
        content=_SCRIPT,
        media_type="text/x-shellscript; charset=utf-8",
        headers={"Cache-Control": "public, max-age=300"},
    )
