  - job_name: "blackbox_http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 60s
    static_configs:
      - targets:
          - https://ai-salex.ru/api/health
          - https://ai-salex.ru/login
          - https://mcp.me-ai.ru/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
